//! Value object.
pub mod constants;
pub mod direction;
pub mod misc;
pub mod person;
pub mod phase;
pub mod piece;
pub mod piece_direction;
pub mod piece_movement;
pub mod piece_type;
pub mod piece_vo;
pub mod piece_vo_master;
pub mod ply;
pub mod region;
pub mod speed_of_light;
pub mod square;
